### ISSUE TITLE
Support for Offline Environment?

### ISSUE THREAD

**Issue by Dviros** [Flangvik/BetterSafetyKatz#4]
Hi @Flangvik,
Thanks for this great tool.

As you're well aware, some environments can't access github.com. Do you think it would be possible to add support for either local compiled mimikatz exe's or even loading it from an attacker's SMB\HTTP paths?

Thanks again!
Dviros

**Comment by clubby789** [comment]
I added custom url support in #5

**Comment by Flangvik** [comment]
Sorry for the late response peeps, need to activate my alerts on GitHub. Il look into this

**Comment by Dviros** [comment]
@clubby789 PR looks good afaik.

**Comment by Flangvik** [comment]
Updated for local path fetch as well, closing. Thanks for input @Dviros @clubby789
